---
- hosts: external
  gather_facts: False
  plugin: aws_ec2

  aws_access_key: { lookup('env','AWS_ACCESS_KEY_ID') }
  aws_secret_key: { lookup('env','AWS_SECRET_KEY_ID') }
  regions:
    - eu-west-1
  filters:
    tag:Environment: Stefan.Testing.Env
